on:
  workflow_call:
jobs:
  unittest:
    strategy:
      matrix:
        version: [18, 20]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build strapi-plugin-translate
        run: npm run build --workspace strapi-plugin-translate
      - name: run tests
        run: npm run test
      - uses: codecov/codecov-action@v5
        with:
          files: ./plugin/coverage/clover.xml,./providers/deepl/coverage/clover.xml,./providers/libretranslate/coverage/clover.xml
          flags: unittests
          name: codecov-umbrella
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: test report
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: unittest report (node=${{ matrix.version }}) # Name of the check run which will be created
          path: reports/jest-*.xml # Path to test results
          reporter: jest-junit # Format of test results
