on:
  workflow_call:
jobs:
  unittest:
    strategy:
      matrix:
        version: [18, 20]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
          cache: 'yarn'
      - run: yarn
      - run: yarn test
      - uses: codecov/codecov-action@v5
        with:
          files: ./plugin/coverage/clover.xml,./providers/deepl/coverage/clover.xml,./providers/libretranslate/coverage/clover.xml
          flags: unittests
          name: codecov-umbrella
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
